spring.application.name=mvp
spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=mvp_database
spring.datasource.username=sa
spring.datasource.password=StrongPass1234$
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
logging.level.root=DEBUG
logging.file.name=MvpApp.log
jwt.expiration=600000
jwt.secret=9D0EB6B1C2E1FAD0F53A248F6C3B5E4E2F6D8G3H1I0J7K4L1M9N2O3P5Q0R7S9T1U4V2W6X0Y3Z
server.error.whitelabel.enabled=false
server.port=3050